### ISSUE TITLE
Where is requirements.txt located?

### ISSUE THREAD

**Issue by sincak** [TheProjectsGuy/MR21-CS7.503#2]
Has requirements.txt been removed permanently?

**Comment by TheProjectsGuy** [comment]
Hey @sincak, I use an anaconda environment to handle the dependencies of this repository. The [anaconda-env.yml](https://github.com/TheProjectsGuy/MR21-CS7.503/blob/main/anaconda-env.yml) file contains the packages to install. 
Since it has about 16 dependencies, you could search for how to install them using only `pip`. I prefer to use `conda` for anaconda environments.
Are you pointing to some file in a commit that was removed in subsequent commits?

**Comment by TheProjectsGuy** [comment]
I was talking about the following dependencies. Most are very common and should have installation methods for `pip`. I'd suggest manually installing it package by package.
https://github.com/TheProjectsGuy/MR21-CS7.503/blob/76a3ec430aae23e4043d4d14bca2b60024320931/anaconda-env.yml#L7-L22

**Comment by sincak** [comment]
Sorry - and thank you!
